### ISSUE TITLE
Some general feedback

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/x-ray-goggles#278]
I used Goggles for the first time with my students and demonstrated it for PD.

 For my students the new copy is great. Nobody really did the sample activity so I don't have much feedback there.

The install page worked well. Still run into a good majority of people who do not have the bookmarks bar displaying. It seems too be the default option on many computers. I am thinking what if we linked to a separate page that demonstrates how to view the bookmark browser in Firefox, Chrome, Explorer, Safari, and Edge. I wouldn't want to crowd the page but was a huge bottleneck for me.

Students also had no idea where the projects lived. The page looked so similar to thimble and teach they expected to have a my projects section. They wanted to know where published projects go and how to get back to them.

This also happened when they did not finish projects. They had no idea how to get back. I told them to publish the project and then use x-ray goggles to remix their remix. This is not ideal.

For the PD side things went well. Again the browser bookmark bar issue. 

The one area that messed teachers up was the warning message on the old webmaker teaching kits that are listed on goggles.mozilla.org. They would ask if goggles was no longer supported. I think this issue has already been filed in the mozilla learning repo.

I know most of the heartbeats are quite full but I feel like maybe we did not give goggles the launch it deserved. 

- Maybe after the newsletter CTA we should include a Goggles CTA on teach.mozilla.org
- Highlight Goggles release in the first #teachtheweb newsletter
- Mention it in the relaunched community calls in March
- We could host a #goggleschat like we did with Thimble
- Maybe include a Goggles activity in either the encryption campaign or the upcoming campus campaign.

Just a few ideas. Realize there a bunch of issues here. Feel free to close this anytime.

**Comment by Pomax** [comment]
cc @hannahkane

**Comment by cassiemc** [comment]
Lots of great feedback here, thanks @jgmac1106. Nothing like testing this in real life.

**Comment by hannahkane** [comment]
Thanks, @jgmac1106. Awesome feedback. Some responses:
 * displaying the bookmarks bar: The instructions for Step 1 on the installation page are dynamically generated. We detect the browser and platform and display specific instructions about how to open the bookmark bar based on that. Did people not see those instructions? (Totally possible. Maybe we need to make them louder.)
 * the issue of where to find projects is a big one! There's a ticket for that here: https://github.com/mozilla/teach.mozilla.org/issues/1223. 
 * Met with @ldecoursy and @chadsansing today, and we now have a plan for getting all of our featured projects onto the new Thimble, so they don't display that warning. @ldecoursy - we should make sure to include the three featured Goggles projects in that plan.
 * Great ideas about promoting Goggles. We specifically didn't do a launch since the tool itself didn't change significantly—we improved the homepage, added a tutorial, and moved it to a new home, but we didn't change any of the core features. We are, however, planning to include mention in the upcoming newsletter, and we have tweeted about it. Not sure I know where you're referring to when you say "after the newsletter CTA." Do you mean on the [Community page](https://teach.mozilla.org/community)? Interesting idea to do a #goggleschat. Curious to know what @ldecoursy and @KGorr think of that.

**Comment by jgmac1106** [comment]
Thanks @hannahkane 

The bookmark bar is clear as day. Not sure how so many people got confused. It is probably me not knowing it was dynamic. That is a really cool feature. I have no idea why people missed it. I will be trying with my clubs next week or so. I will try again and do some cognitive labbing "think alouds" if I se it happen again.

@ldecoursy It is only the hacking my media project non Thimble. Remix science for girls needs a lot of work. It still points to goggles on Hackasaruas (RIP old friend). There are many other outdated links and/or branding. It might be easier to develop a new activity. Had the idea of connecting it to #nextprez. Maybe remix a candidates webpage to change their positions.

Only reason I brought up promoting Goggles is the note from @adamlofting that goggles.webmaker.org is still getting 35K hits a month. Beyond trying to track down the referrals maybe we need to get word out. 

In terms of the CTA I meant on teach.mozilla.org. I think the current pop-up is still pledge to teach. I thought sign up for newsletter was next. I was thinking after that.

**Comment by Pomax** [comment]
Wait, something still points to hackasaurus? O_o We switched from that four years ago, so even in previous incarnations of the goggles that should have already not been the case. Do you have the link for that project handy?

**Comment by jgmac1106** [comment]
It is a link on on the third project "remix science for girls"  the link to
install goggles points to hackasaurus. I did not test if there is redirect.

Once "remix science for girls" is updated it should be fine. Addressed
here: https://github.com/mozilla/teach.mozilla.org/issues/1223

**Comment by KGorr** [comment]
I like the idea of a #goggleschat. We'll have to discuss how that can align with our new Editorial calendar and monthly communication themes, but it seems that we could easily fit it in. Thanks @jgmac1106 for the great idea and feedback!
